/**
 * COMP4537 - Lab 4
 * Names: Andy Lau #A01192350 - Victor Liu #A00971668
 * Date: 2024-10-20
 * 
 * serverUtils.js
 * 
 * Note: code generated by ChatGPT has been commented where used.
 */

const fs = require('fs');


/**
 * Utility function to serve html files.
 * 
 * @param {*} res response object
 * @param {*} filePath the path to the html file
 * @param {*} contentType content type
 * @param {*} statusCode status code, default is 200
 */
function serveStaticFile(res, filePath, contentType, statusCode=200) {
    fs.readFile(filePath, (err, data) => {
        if (err) {
            console.log(err);
            res.writeHead(500, { 'Content-Type': 'text/plain' });
            res.end('500 Internal Server Error');
        } else {
            res.writeHead(statusCode, { 'Content-Type': contentType });
            res.end(data);
        }
    });
}

module.exports = { serveStaticFile }