/**
 * COMP4537 - Lab 1
 * Name: Victor Liu #A00971668 - Set C
 * Date: 2024-09-15
 * 
 * note.js
 * 
 * A note object.
 * 
 * note: code generated by ChatGPT has been commented where used.
 */


class Note {
    constructor(id, top = 50, left = 50) {
        this.id = id;
        this.isSaved = false;
        this.top = top;  // ChatGPT: the default value should be 50
        this.left = left;  // ChatGPT: the default value should be 50

        this.noteElement = this.createNoteElement();
        this.setPosition(this.noteElement);  // ChatGPT: set the position of the note
    }

    createNoteElement() {
        const noteDiv = document.createElement('div');
        noteDiv.classList.add('note-base');
        noteDiv.setAttribute('id', this.id);

        
        const textarea = document.createElement('textarea');
        textarea.addEventListener('input', (e) => this.updateText(e));  // ChatGPT: for real-time typing event listener

        noteDiv.appendChild(textarea);

        return noteDiv;
    }

    updateText(event) {
        const text = event.target.value;
        console.log(`Note ${this.id} content: `, text);
    }


    // ChatGPT: helper function to set position values
    setPosition(element) {
        element.style.top = `${this.top}px`;
        element.style.left = `${this.left}px`;
    }

    getNoteElement() {
        return this.noteElement;
    }

    // ChatGPT: Static method to position notes relative to each other
    static getNextPosition(lastNote) {
        const spacing = 50; // Distance between notes
        return {
            top: lastNote.top,
            left: lastNote.left + lastNote.noteElement.offsetWidth + spacing
        };
    }
}