/**
 * COMP4537 - Lab 1
 * Name: Victor Liu #A00971668 - Set C
 * Date: 2024-09-15
 * 
 * note.js
 * 
 * The NoteManager class handles the notes.
 * 
 * note: code generated by ChatGPT has been commented where used.
 */


class NoteManager {
    constructor() {
        this.notes = [];
        this.nextId = 1;
        this.loadNotes(); 
    }

    createNote(top, left) {
        const note = new Note(this.nextId++, top, left);
        this.notes.push(note);
        this.saveNotes(); 
        return note;
    }

    getNotes() {
        return this.notes.map((note) => note.noteToJSON());  //ChatGPT: syntax to get all notes as JSON objects
    }

    saveNotes() {
        console.log("Saving notes to local storage..");
        const notes = this.getNotes();
        localStorage.setItem("notes", JSON.stringify(notes));
        const event = new Event("notesSaved");
        document.dispatchEvent(event);
    }

    
    loadNotes() {
        const savedNotes = JSON.parse(localStorage.getItem("notes")) || [];
        savedNotes.forEach(noteData => {
            const note = new Note(noteData.id, noteData.top, noteData.left);
            note.text = noteData.text; 
            this.notes.push(note);
            document.getElementById("notes-container").appendChild(note.getNoteElement());
            note.updateTextFromElement(); // Update text in the textarea after creating and appending the note element
        });
    }
}
