/**
 * COMP4537 - Lab 3
 * Name: Victor Liu #A00971668 - Set C
 * Date: 2024-09-29
 * 
 * index.js
 * 
 * Note: code generated by ChatGPT has been commented where used.
 */



//ChatGPT: implement dynamic text on client
const currentDomain = window.location.hostname;
const currentProtocol = window.location.protocol;

// Construct the full URL
const fullUrl = `${currentProtocol}//${currentDomain}/COMP4537/labs/3/getDate`;

// Replace the content of the <code> element with id "dynamic-url"
document.getElementById('dynamic-url').textContent = fullUrl;