/**
 * COMP4537 - Lab 5
 * Names: Andy Lau #A01192350 - Victor Liu #A00971668
 * Group: C1
 * Date: 2024-10-13
 *
 * utils.js
 *
 * Note: code generated by ChatGPT has been commented where used.
 */

/**
 * Gets date and time.
 * 
 * @returns the current date and time as a string (Format: yyyy-mm-dd hh:mm:ss)
 */
function getCurrentTimestamp() {
    const now = new Date();

    //ChatGPT: asked how to format date as yyyy-mm-dd
    const year = now.getFullYear();
    const month = String(now.getMonth() + 1).padStart(2, '0'); // Months are zero-based
    const day = String(now.getDate()).padStart(2, '0');
    
    
    const hours = String(now.getHours()).padStart(2, '0');
    const minutes = String(now.getMinutes()).padStart(2, '0');
    const seconds = String(now.getSeconds()).padStart(2, '0');
    
    
    return `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`;
  }
  
  export { getCurrentTimestamp };